# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_cursos_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='lider',
            field=models.CharField(default='Mohamed', max_length=100),
        ),
    ]
