# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alunos_lider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id_celula', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.CharField(default='Mohamed', max_length=100)),
                ('bairro', models.CharField(default='BDN Tapuapé', max_length=100)),
                ('contato', models.CharField(default='s/ contato', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lista',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='curso',
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='id',
            new_name='id_aluno',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='id',
            new_name='id_curso',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='lider',
        ),
        migrations.AddField(
            model_name='alunos',
            name='observacoes',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='descricao',
            field=models.CharField(default='default', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunos',
            name='celula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Celula'),
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Cursos'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Alunos'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Cursos'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Cursos'),
        ),
    ]
